---
- name: update linux servers
  hosts: all
  tasks:
 
  - name: update the system
    yum:
      name: "*"
      state: latest
    notify:
    - restart
    - pause
    - wait for reboot
  
  handlers:
  
  - name: restart
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0

  - name: pause
    pause:
      seconds: 10

  - name: wait for reboot
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 60